### PR TITLE
Milestone 4: Game Instructions

### PR DESCRIPTION
**Pull request by mariordgez**
In this milestone, these are the features added to the project:
- Added a readme file with proper documentation for the project
- In the readme file, we also gave some sets of instructions on how to play the game
- We implemented the optional changes that were made in the last code review, specifically, we added the condition that a player name should always have at least one letter, the game won't accept only numbers as name input.

### CODE REVIEW

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :red_circle: :stop_sign: 
-------------
Hello, @mariordgez @DanSam5K you did an amazing job in this milestone :clap: 
TO HIGHLIGHT: 
- The branch is descriptive
- The readme is professional
- The repo si professional.
However, there are a few changes to make to complete this milestone. :wrench: are them below :point_down: :eyes: 
--------------
- [x]  Check the minor grammar errors in your readme and in the pull request description.
- [x] On getting started make the step more descriptive. Think about someone that does not know anything about programming. E.g Go to the folder where you want to store the app and run the following command `$ git clone https://github.com/DanSam5K/OOP-Tic-Tac-Toe-Game.git` to clone the repository
- [x] You write 
`Testing
To test the code and start the game, run bin/main.rb file from your terminal.`
You are not testing the code with this command, you are just running the game. So, please fix this text on your readme. You can write only `To run the game run the following command in the terminal`
---------------
Make these required changes and send it again for another review :+1: 
Reach me on SLACK if you have any questions. 
@ Brian SAmmit Cruz Rodriguez
HAPPY CODING!!!! :smile:

**Review by smcommits — APPROVED** [review]
# Status: Approved 👍🏽 

# Hello, team! You have done a great job. The README appears to be informative. Excellent work implementing the changes that the previous reviewer requested. This PR is now approved. You can go ahead and merge the branch. Congratulations and good luck.

**Comment by DanSam5K** [comment]
Noted! 👍 
- We will look into the corrections and make sure we address the concerns. ✍️
Thank you🤝

**Comment by DanSam5K** [comment]
Noted! 👍

We will look into the corrections and make sure we address the concerns. ✍️
Thank you🤝

**Comment by DanSam5K** [comment]
Thank you @smcommits 🤝
🙌🙌

**Pull request merged**
